<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="service" nsURI="http://www.abchip.org/mimo/biz/service" nsPrefix="biz-service">
  <eSubpackages name="accounting" nsURI="http://www.abchip.org/mimo/biz/service/accounting"
      nsPrefix="biz-accounting">
    <eClassifiers xsi:type="ecore:EClass" name="GetTotalInvoice">
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceMethodRequest">
        <eTypeArguments eClassifier="ecore:EClass ../../org.abchip.mimo.biz.model/model/biz-model.ecore#//accounting/invoice/Invoice"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetInvoiceStatus">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="invoiceId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="paidDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//accounting/SetInvoiceStatusResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetInvoiceStatusResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="invoiceTypeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldStatusId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetPaymentStatus">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="paymentId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//accounting/SetPaymentStatusResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetPaymentStatusResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse"/>
    <eClassifiers xsi:type="ecore:EClass" name="UpdatePaymentApplicationDef">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="invoiceId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="paymentId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//accounting/UpdatePaymentApplicationDefResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UpdatePaymentApplicationDefResponse"
        eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse"/>
    <eClassifiers xsi:type="ecore:EClass" name="Addtax">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="invoiceId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//accounting/AddtaxResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AddtaxResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse"/>
  </eSubpackages>
  <eSubpackages name="catalina" nsURI="http://www.abchip.org/mimo/biz/service/catalina"
      nsPrefix="biz-catalina"/>
  <eSubpackages name="common" nsURI="http://www.abchip.org/mimo/biz/service/common"
      nsPrefix="biz-common">
    <eClassifiers xsi:type="ecore:EClass" name="GetCommonDefault">
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//common/GetCommonDefaultResponse"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//java/JavaCallable">
        <eTypeArguments eClassifier="#//common/GetCommonDefaultResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GetCommonDefaultResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse">
      <eStructuralFeatures xsi:type="ecore:EReference" name="currencyUom" lowerBound="1"
          eType="ecore:EClass ../../org.abchip.mimo.biz.model/model/biz-model.ecore#//common/uom/Uom"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="countryGeo" lowerBound="1"
          eType="ecore:EClass ../../org.abchip.mimo.biz.model/model/biz-model.ecore#//common/geo/Geo"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="content" nsURI="http://www.abchip.org/mimo/biz/service/content"
      nsPrefix="biz-content"/>
  <eSubpackages name="entity" nsURI="http://www.abchip.org/mimo/biz/service/entity"
      nsPrefix="biz-entity">
    <eClassifiers xsi:type="ecore:EClass" name="ConvertSeeds">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="readers" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateTenant" abstract="true">
      <eOperations name="getTenantId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getTenantName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="loadSeeds" eExceptions="ecore:EDataType ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceException"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbType" lowerBound="1"
          eType="#//entity/DatabaseType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="update" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//java/JavaCallable">
        <eTypeArguments eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateTenantDemo" eSuperTypes="#//entity/CreateTenant"/>
    <eClassifiers xsi:type="ecore:EClass" name="CreateTenantMaster">
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//java/JavaCallable">
        <eTypeArguments eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateTenantParty" eSuperTypes="#//entity/CreateTenant">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tenantId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tenantName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="partyId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateTenantTest" eSuperTypes="#//entity/CreateTenant"/>
    <eClassifiers xsi:type="ecore:EEnum" name="DatabaseType">
      <eLiterals name="Derby" literal="D"/>
      <eLiterals name="PostgreSQL" literal="P"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExportEntities">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathTo" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="humanres" nsURI="http://www.abchip.org/mimo/biz/service/humanres"
      nsPrefix="biz-humanres"/>
  <eSubpackages name="manufacturing" nsURI="http://www.abchip.org/mimo/biz/service/manufacturing"
      nsPrefix="biz-manufacturing"/>
  <eSubpackages name="marketing" nsURI="http://www.abchip.org/mimo/biz/service/marketing"
      nsPrefix="biz-marketing"/>
  <eSubpackages name="order" nsURI="http://www.abchip.org/mimo/biz/service/order"
      nsPrefix="biz-order">
    <eClassifiers xsi:type="ecore:EClass" name="ChangeOrderStatus">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeReason" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="setItemStatus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//order/ChangeOrderStatusResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ChangeOrderStatusResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="grandTotal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="needsInventoryIssuance"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldStatusId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderStatusId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderTypeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReserveStoreInventory">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="facilityId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderItemSeqId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="productId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="productStoreId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shipGroupSeqId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//order/ReserveStoreInventoryResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReserveStoreInventoryResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantityNotReserved"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResetGrandTotal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//order/ResetGrandTotalResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResetGrandTotalResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse"/>
    <eClassifiers xsi:type="ecore:EClass" name="RecalcTaxTotal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderItemSeqId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//order/RecalcTaxTotalResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RecalcTaxTotalResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse"/>
  </eSubpackages>
  <eSubpackages name="party" nsURI="http://www.abchip.org/mimo/biz/service/party"
      nsPrefix="biz-party">
    <eClassifiers xsi:type="ecore:EClass" name="CreatePartyContactMech">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowSolicitation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="comments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contactMechId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contactMechPurposeTypeId"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contactMechTypeId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="infoString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="monthsWithContactMech"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="partyId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleTypeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="thruDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="verified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="yearsWithContactMech"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//party/CreatePartyContactMechResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreatePartyContactMechResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contactMechId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreatePartyContactMechPurpose">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contactMechId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contactMechPurposeTypeId"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromDate" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="partyId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//party/CreatePartyContactMechPurposeResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreatePartyContactMechPurposeResponse"
        eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GetPartyDefault">
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//party/GetPartyDefaultResponse"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//java/JavaCallable">
        <eTypeArguments eClassifier="#//party/GetPartyDefaultResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GetPartyDefaultResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse">
      <eStructuralFeatures xsi:type="ecore:EReference" name="organization" lowerBound="1"
          eType="ecore:EClass ../../org.abchip.mimo.biz.model/model/biz-model.ecore#//party/party/Party"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="accountingPreference"
          lowerBound="1" eType="ecore:EClass ../../org.abchip.mimo.biz.model/model/biz-model.ecore#//accounting/ledger/PartyAcctgPreference"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="passport" nsURI="http://www.abchip.org/mimo/biz/service/passport"
      nsPrefix="biz-passport"/>
  <eSubpackages name="product" nsURI="http://www.abchip.org/mimo/biz/service/product"
      nsPrefix="biz-product">
    <eClassifiers xsi:type="ecore:EClass" name="CalcTaxForDisplay">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePrice" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="billToPartyId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="productId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="productStoreId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shippingPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//product/CalcTaxForDisplayResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CalcTaxForDisplayResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priceWithTax" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="taxPercentage" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="taxTotal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CalculateProductPrice">
      <eStructuralFeatures xsi:type="ecore:EReference" name="product" lowerBound="1"
          eType="ecore:EClass ../../org.abchip.mimo.biz.model/model/biz-model.ecore#//product/product/Product"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="currencyUomId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="@general/currency.uom.id.default"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//product/CalculateProductPriceResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CalculateProductPriceResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validPriceFound" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePrice" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="listPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="orderItemPriceInfos"
          upperBound="-1" eType="ecore:EClass ../../org.abchip.mimo.biz.model/model/biz-model.ecore#//order/order/OrderItemPriceInfo"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CalculatePurchasePrice">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="agreementId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="@general/currency.uom.id.default"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="currencyUomId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="@general/currency.uom.id.default"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="partyId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="@general/currency.uom.id.default"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="product" lowerBound="1"
          eType="ecore:EClass ../../org.abchip.mimo.biz.model/model/biz-model.ecore#//product/product/Product"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//product/CalculatePurchasePriceResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CalculatePurchasePriceResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validPriceFound" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="orderItemPriceInfos"
          upperBound="-1" eType="ecore:EClass ../../org.abchip.mimo.biz.model/model/biz-model.ecore#//order/order/OrderItemPriceInfo"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GetProductDefault">
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//product/GetProductDefaultResponse"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//java/JavaCallable">
        <eTypeArguments eClassifier="#//product/GetProductDefaultResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GetProductDefaultResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse">
      <eStructuralFeatures xsi:type="ecore:EReference" name="facilityPostalAddress"
          lowerBound="1" eType="ecore:EClass ../../org.abchip.mimo.biz.model/model/biz-model.ecore#//party/contact/PostalAddress"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="security" nsURI="http://www.abchip.org/mimo/biz/service/security"
      nsPrefix="biz-security">
    <eClassifiers xsi:type="ecore:EClass" name="CheckExternalLoginUser">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessToken" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="@general/currency.uom.id.default"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="@general/currency.uom.id.default"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="@general/currency.uom.id.default"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="@general/currency.uom.id.default"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="@general/currency.uom.id.default"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="@general/currency.uom.id.default"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceRequest">
        <eTypeArguments eClassifier="#//security/CheckExternalLoginUserResponse"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CheckExternalLoginUserResponse" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//service/ServiceResponse"/>
  </eSubpackages>
  <eSubpackages name="service" nsURI="http://www.abchip.org/mimo/biz/service/service"
      nsPrefix="biz-service"/>
  <eSubpackages name="shipment" nsURI="http://www.abchip.org/mimo/biz/service/shipment"
      nsPrefix="biz-shipment"/>
  <eSubpackages name="webapp" nsURI="http://www.abchip.org/mimo/biz/service/webapp"
      nsPrefix="biz-webapp"/>
  <eSubpackages name="workeffort" nsURI="http://www.abchip.org/mimo/biz/service/workeffort"
      nsPrefix="biz-workeffort"/>
</ecore:EPackage>
